### ISSUE TITLE
While editing product, comments cant be show for edit.

### ISSUE THREAD

**Issue by mikeldavilla** [Kudratullah/Block-Editor-For-WooCommerce#1]
First of all the plugin is usefull for me and is helping me a lot. Please update the plugin to the last version of wordpress. Back to the issue while editing product page in block editor the <show comment> at the bottom of page dont work. Before using the block editor i could click on it and edit woo comments but now with the block editor, doesnt work.

**Comment by Kudratullah** [comment]
Hi @mikeldavilla 

Thanks for the report & sorry for the delayed response. Can you please add the information listed below to debug and reproduce the problem on my setup:

- list of installed plugin.
- active theme name and url if possible.
- screenshot of console (if any error logged there related to the issue).

**Comment by mikeldavilla** [comment]
PHP Version : 7.2.30

MySQL Version : 5.5.5

Server Info : Apache

Default Timezone : UTC

WP Version : 5.4.1

WP Debug : ❌

WP Language : en_US

WP Multisite : ❌

WP Memory Limit : 40MMB

WP Table Prefix : wpjs_

WP Timezone : , GMT : 0

Registered Post Stati :
PHP Information
PHP Post Max Size : 512M

PHP Time Limit : 360

PHP Max Input Vars : 2000000

PHP Memory Limit : 4096M

PHP Upload Max Size : 512M

PHP Upload Max Filesize : 512M

PHP Arg Separator : &

PHP Allow URL File Open : ✔

DISPLAY ERRORS :

FSOCKOPEN : ✔

cURL : ✔

SOAP Client : ✔

SUHOSIN : ❌

Session : ❌

Session Name : PHPSESSID

Cookie Path : /

Save Path : /tmp

Use Cookies : ✔

Use Only Cookies : ✔

Active Theme
Theme Name : Online Shop

Theme Version : 2.0.2

Theme Author : acmethemes

Theme Author URI : https://www.acmethemes.com/

Child Theme : ❌

Plugins
_Active_
alidswoo/alidswoo.php
block-editor-for-woocommerce/block-editor-for-woocommerce.php
contact-form-7/wp-contact-form-7.php
crisp/crisp.php
flamingo/flamingo.php
gutentor/gutentor.php
jetpack/jetpack.php
loco-translate/loco.php
woocommerce-quick-buy/wc-quick-buy.php
really-simple-ssl/rlrsssl-really-simple-ssl.php
wpcf7-recaptcha/wpcf7-recaptcha.php
wp-smushit/wp-smush.php
updraftplus/updraftplus.php
woocommerce/woocommerce.php
wordfence/wordfence.php
wp-mail-smtp/wp_mail_smtp.php
yith-woocommerce-wishlist/init.php
_Installed, not active_
acme-demo-setup/acme-demo-setup.php
woocommerce-pdf-invoices-packing-slips/woocommerce-pdf-invoices-packingslips.php
