### ISSUE TITLE
Please Declare Compatibility with HOPS

### ISSUE THREAD

**Issue by a3rev** [Kudratullah/Block-Editor-For-WooCommerce#3]
Hello,

Do you have any intention of putting out an update that declares compatibility with WooCommerce HOPS? I see that a Ticket was opened on the [WordPress support forum](https://wordpress.org/support/topic/please-declare-hpos-support/) almost 2 months ago, but there has been no update on the plugin for 4 months now. 

Thank you
Steve

**Comment by Kudratullah** [comment]
Sorry for the delay. I'll try on this weekend to release an update.

Thanks for sharing the code on WordPress support forum.

**Comment by a3rev** [comment]
@Kudratullah 

Thank you - that would be excellent.
